version: "3.8"

services:
  jekyll:
    image: jekyll
    volumes: 
      - jekyll_compose_out:/output
      - ./minimal-mistakes:/input
    restart: always
  webserver:
    image: webserver:2.0
    ports:
      - "80:81"
    volumes:
      - jekyll_compose_out:/content
    depends_on: 
      - jekyll

networks: 
  jekyll_compose:

volumes:
  jekyll_compose_out: